# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\kaste\Desktop\Uni\AgentsAndInterfaces\CourseProject\Interface\Setup_Main.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainSetupWindow(object):
    globalIndex = 1

    def setupUi(self, MainSetupWindow):
        MainSetupWindow.setObjectName("MainSetupWindow")
        MainSetupWindow.resize(600, 400)
        MainSetupWindow.setMinimumSize(QtCore.QSize(600, 400))
        MainSetupWindow.setMaximumSize(QtCore.QSize(600, 400))
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.page)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(390, 350, 195, 30))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.buttonCancel2 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.buttonCancel2.setObjectName("buttonCancel2")
        self.horizontalLayout.addWidget(self.buttonCancel2)

        self.buttonNext2 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.buttonNext2.setObjectName("buttonNext2")
        self.horizontalLayout.addWidget(self.buttonNext2)
        self.buttonNext2.clicked.connect(lambda:MainSetupWindow.setCurrentIndex(1))

        self.label = QtWidgets.QLabel(self.page)
        self.label.setGeometry(QtCore.QRect(220, 140, 351, 111))
        self.label.setScaledContents(False)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.page)
        self.label_2.setGeometry(QtCore.QRect(220, 10, 361, 101))
        self.label_2.setStyleSheet("font: bold 12pt \"MS Shell Dlg 2\";")
        self.label_2.setScaledContents(False)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.line = QtWidgets.QFrame(self.page)
        self.line.setGeometry(QtCore.QRect(-10, 320, 611, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.graphicsLabel = QtWidgets.QLabel(self.page)
        self.graphicsLabel.setGeometry(QtCore.QRect(0, 20, 231, 301))
        self.graphicsLabel.setText("")
        self.graphicsLabel.setPixmap(QtGui.QPixmap("AwesomeLogo2.png"))
        self.graphicsLabel.setObjectName("graphicsLabel")
        self.line_3 = QtWidgets.QFrame(self.page)
        self.line_3.setGeometry(QtCore.QRect(270, 320, 611, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.page)
        self.line_4.setGeometry(QtCore.QRect(220, 100, 361, 20))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        MainSetupWindow.addWidget(self.page)
        self.page1 = QtWidgets.QWidget()
        self.page1.setObjectName("page1")
        self.line_2 = QtWidgets.QFrame(self.page1)
        self.line_2.setGeometry(QtCore.QRect(-10, 320, 611, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.page1)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(390, 350, 195, 30))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.buttonBack3 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.buttonBack3.setObjectName("buttonBack3")
        self.horizontalLayout_3.addWidget(self.buttonBack3)

        self.buttonNext3 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.buttonNext3.setObjectName("buttonNext3")
        self.buttonNext3.clicked.connect(lambda: MainSetupWindow.setCurrentIndex(int(self.globalIndex)))

        self.horizontalLayout_3.addWidget(self.buttonNext3)
        self.label_3 = QtWidgets.QLabel(self.page1)
        self.label_3.setGeometry(QtCore.QRect(20, 50, 511, 51))
        self.label_3.setObjectName("label_3")

        self.installRadioFull = QtWidgets.QRadioButton(self.page1)
        self.installRadioFull.setGeometry(QtCore.QRect(50, 110, 241, 20))
        self.installRadioFull.setStyleSheet("font: bold 8pt \"MS Shell Dlg 2\";")
        self.installRadioFull.setChecked(1)
        self.installRadioFull.setObjectName("installRadioFull")
        self.installRadioFull.clicked.connect(self.radioCheck1)

        self.label_4 = QtWidgets.QLabel(self.page1)
        self.label_4.setGeometry(QtCore.QRect(20, 10, 241, 61))
        self.label_4.setStyleSheet("font: bold 10pt \"MS Shell Dlg 2\";")
        self.label_4.setObjectName("label_4")

        self.installRadioCustom = QtWidgets.QRadioButton(self.page1)
        self.installRadioCustom.setGeometry(QtCore.QRect(50, 140, 311, 20))
        self.installRadioCustom.setObjectName("installRadioCustom")
        self.installRadioCustom.clicked.connect(self.radioCheck2)

        self.line_7 = QtWidgets.QFrame(self.page1)
        self.line_7.setGeometry(QtCore.QRect(0, 90, 601, 16))
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        MainSetupWindow.addWidget(self.page1)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.label_5 = QtWidgets.QLabel(self.page_2)
        self.label_5.setGeometry(QtCore.QRect(20, 10, 241, 61))
        self.label_5.setStyleSheet("font: bold 10pt \"MS Shell Dlg 2\";")
        self.label_5.setObjectName("label_5")
        self.checkBox = QtWidgets.QCheckBox(self.page_2)
        self.checkBox.setEnabled(False)
        self.checkBox.setGeometry(QtCore.QRect(40, 60, 551, 21))
        self.checkBox.setStyleSheet("font: bold 9pt \"MS Shell Dlg 2\";")
        self.checkBox.setCheckable(True)
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.page_2)
        self.checkBox_2.setGeometry(QtCore.QRect(50, 100, 461, 21))
        self.checkBox_2.setChecked(True)
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.page_2)
        self.checkBox_3.setGeometry(QtCore.QRect(50, 130, 461, 21))
        self.checkBox_3.setChecked(True)
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_4 = QtWidgets.QCheckBox(self.page_2)
        self.checkBox_4.setGeometry(QtCore.QRect(50, 160, 461, 21))
        self.checkBox_4.setChecked(True)
        self.checkBox_4.setObjectName("checkBox_4")
        self.checkBox_5 = QtWidgets.QCheckBox(self.page_2)
        self.checkBox_5.setGeometry(QtCore.QRect(50, 190, 461, 21))
        self.checkBox_5.setChecked(True)
        self.checkBox_5.setObjectName("checkBox_5")
        self.checkBox_6 = QtWidgets.QCheckBox(self.page_2)
        self.checkBox_6.setGeometry(QtCore.QRect(50, 220, 461, 21))
        self.checkBox_6.setChecked(True)
        self.checkBox_6.setObjectName("checkBox_6")
        self.checkBox_7 = QtWidgets.QCheckBox(self.page_2)
        self.checkBox_7.setGeometry(QtCore.QRect(50, 250, 461, 21))
        self.checkBox_7.setChecked(True)
        self.checkBox_7.setObjectName("checkBox_7")
        self.checkBox_8 = QtWidgets.QCheckBox(self.page_2)
        self.checkBox_8.setGeometry(QtCore.QRect(50, 280, 461, 21))
        self.checkBox_8.setChecked(True)
        self.checkBox_8.setObjectName("checkBox_8")
        self.checkBox_9 = QtWidgets.QCheckBox(self.page_2)
        self.checkBox_9.setGeometry(QtCore.QRect(260, 220, 461, 21))
        self.checkBox_9.setChecked(True)
        self.checkBox_9.setObjectName("checkBox_9")
        self.checkBox_11 = QtWidgets.QCheckBox(self.page_2)
        self.checkBox_11.setGeometry(QtCore.QRect(210, 280, 461, 21))
        self.checkBox_11.setChecked(True)
        self.checkBox_11.setObjectName("checkBox_11")
        self.checkBox_12 = QtWidgets.QCheckBox(self.page_2)
        self.checkBox_12.setGeometry(QtCore.QRect(500, 270, 461, 21))
        self.checkBox_12.setChecked(True)
        self.checkBox_12.setObjectName("checkBox_12")
        self.checkBox_13 = QtWidgets.QCheckBox(self.page_2)
        self.checkBox_13.setGeometry(QtCore.QRect(260, 250, 461, 21))
        self.checkBox_13.setChecked(True)
        self.checkBox_13.setObjectName("checkBox_13")
        self.checkBox_14 = QtWidgets.QCheckBox(self.page_2)
        self.checkBox_14.setGeometry(QtCore.QRect(260, 100, 461, 21))
        self.checkBox_14.setChecked(True)
        self.checkBox_14.setObjectName("checkBox_14")
        self.checkBox_15 = QtWidgets.QCheckBox(self.page_2)
        self.checkBox_15.setGeometry(QtCore.QRect(250, 270, 121, 21))
        self.checkBox_15.setChecked(True)
        self.checkBox_15.setObjectName("checkBox_15")
        self.checkBox_16 = QtWidgets.QCheckBox(self.page_2)
        self.checkBox_16.setGeometry(QtCore.QRect(260, 190, 461, 21))
        self.checkBox_16.setChecked(True)
        self.checkBox_16.setObjectName("checkBox_16")
        self.checkBox_18 = QtWidgets.QCheckBox(self.page_2)
        self.checkBox_18.setGeometry(QtCore.QRect(260, 130, 461, 21))
        self.checkBox_18.setChecked(True)
        self.checkBox_18.setObjectName("checkBox_18")
        self.checkBox_20 = QtWidgets.QCheckBox(self.page_2)
        self.checkBox_20.setGeometry(QtCore.QRect(390, 160, 461, 21))
        self.checkBox_20.setChecked(True)
        self.checkBox_20.setObjectName("checkBox_20")
        self.checkBox_21 = QtWidgets.QCheckBox(self.page_2)
        self.checkBox_21.setGeometry(QtCore.QRect(260, 160, 461, 21))
        self.checkBox_21.setChecked(True)
        self.checkBox_21.setObjectName("checkBox_21")
        self.checkBox_22 = QtWidgets.QCheckBox(self.page_2)
        self.checkBox_22.setGeometry(QtCore.QRect(360, 300, 461, 21))
        self.checkBox_22.setChecked(True)
        self.checkBox_22.setObjectName("checkBox_22")
        self.checkBox_23 = QtWidgets.QCheckBox(self.page_2)
        self.checkBox_23.setGeometry(QtCore.QRect(60, 310, 141, 21))
        self.checkBox_23.setChecked(True)
        self.checkBox_23.setObjectName("checkBox_23")
        self.checkBox_24 = QtWidgets.QCheckBox(self.page_2)
        self.checkBox_24.setGeometry(QtCore.QRect(310, 180, 461, 21))
        self.checkBox_24.setChecked(True)
        self.checkBox_24.setObjectName("checkBox_24")
        self.checkBox_25 = QtWidgets.QCheckBox(self.page_2)
        self.checkBox_25.setGeometry(QtCore.QRect(340, 240, 461, 21))
        self.checkBox_25.setChecked(True)
        self.checkBox_25.setObjectName("checkBox_25")
        self.checkBox_26 = QtWidgets.QCheckBox(self.page_2)
        self.checkBox_26.setGeometry(QtCore.QRect(410, 100, 461, 21))
        self.checkBox_26.setChecked(True)
        self.checkBox_26.setObjectName("checkBox_26")
        self.checkBox_27 = QtWidgets.QCheckBox(self.page_2)
        self.checkBox_27.setGeometry(QtCore.QRect(370, 260, 121, 21))
        self.checkBox_27.setChecked(True)
        self.checkBox_27.setObjectName("checkBox_27")
        self.checkBox_28 = QtWidgets.QCheckBox(self.page_2)
        self.checkBox_28.setGeometry(QtCore.QRect(440, 150, 461, 21))
        self.checkBox_28.setChecked(True)
        self.checkBox_28.setObjectName("checkBox_28")
        self.checkBox_29 = QtWidgets.QCheckBox(self.page_2)
        self.checkBox_29.setGeometry(QtCore.QRect(510, 310, 281, 21))
        self.checkBox_29.setChecked(True)
        self.checkBox_29.setObjectName("checkBox_29")
        self.checkBox_30 = QtWidgets.QCheckBox(self.page_2)
        self.checkBox_30.setGeometry(QtCore.QRect(460, 230, 461, 21))
        self.checkBox_30.setChecked(True)
        self.checkBox_30.setObjectName("checkBox_30")
        self.checkBox_31 = QtWidgets.QCheckBox(self.page_2)
        self.checkBox_31.setGeometry(QtCore.QRect(440, 210, 461, 21))
        self.checkBox_31.setChecked(True)
        self.checkBox_31.setObjectName("checkBox_31")
        self.checkBox_32 = QtWidgets.QCheckBox(self.page_2)
        self.checkBox_32.setGeometry(QtCore.QRect(470, 180, 461, 21))
        self.checkBox_32.setChecked(True)
        self.checkBox_32.setObjectName("checkBox_32")
        self.checkBox_33 = QtWidgets.QCheckBox(self.page_2)
        self.checkBox_33.setGeometry(QtCore.QRect(470, 120, 461, 21))
        self.checkBox_33.setChecked(True)
        self.checkBox_33.setObjectName("checkBox_33")
        self.checkBox_34 = QtWidgets.QCheckBox(self.page_2)
        self.checkBox_34.setGeometry(QtCore.QRect(460, 290, 461, 21))
        self.checkBox_34.setChecked(True)
        self.checkBox_34.setObjectName("checkBox_34")
        self.checkBox_35 = QtWidgets.QCheckBox(self.page_2)
        self.checkBox_35.setGeometry(QtCore.QRect(390, 130, 461, 21))
        self.checkBox_35.setChecked(True)
        self.checkBox_35.setObjectName("checkBox_35")
        self.checkBox_36 = QtWidgets.QCheckBox(self.page_2)
        self.checkBox_36.setGeometry(QtCore.QRect(220, 300, 141, 21))
        self.checkBox_36.setChecked(True)
        self.checkBox_36.setObjectName("checkBox_36")
        self.line_5 = QtWidgets.QFrame(self.page_2)
        self.line_5.setGeometry(QtCore.QRect(0, 90, 601, 16))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_6 = QtWidgets.QFrame(self.page_2)
        self.line_6.setGeometry(QtCore.QRect(0, 320, 611, 20))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.page_2)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(390, 350, 195, 30))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.buttonBack4 = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.buttonBack4.setObjectName("buttonBack4")
        self.horizontalLayout_4.addWidget(self.buttonBack4)
        self.buttonNext4 = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.buttonNext4.setObjectName("buttonNext4")
        self.horizontalLayout_4.addWidget(self.buttonNext4)
        MainSetupWindow.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.greenBtn = QtWidgets.QPushButton(self.page_3)
        self.greenBtn.setGeometry(QtCore.QRect(390, 320, 221, 81))
        self.greenBtn.setAutoFillBackground(False)
        self.greenBtn.setStyleSheet("border: none;\n"
"")
        self.greenBtn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("InstallButtonHov.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon.addPixmap(QtGui.QPixmap("InstallButtonHov.png"), QtGui.QIcon.Active, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap("InstallButtonHov.png"), QtGui.QIcon.Disabled, QtGui.QIcon.On)
        icon.addPixmap(QtGui.QPixmap("InstallButton.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap("InstallButtonHov.png"), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap("InstallButtonHov.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        icon.addPixmap(QtGui.QPixmap("InstallButtonHov.png"), QtGui.QIcon.Active, QtGui.QIcon.On)
        self.greenBtn.setIcon(icon)
        self.greenBtn.setIconSize(QtCore.QSize(160, 150))
        self.greenBtn.setCheckable(False)
        self.greenBtn.setChecked(False)
        self.greenBtn.setObjectName("greenBtn")
        self.label_6 = QtWidgets.QLabel(self.page_3)
        self.label_6.setGeometry(QtCore.QRect(20, 10, 421, 61))
        self.label_6.setStyleSheet("font: bold 10pt \"MS Shell Dlg 2\";")
        self.label_6.setObjectName("label_6")
        self.line_8 = QtWidgets.QFrame(self.page_3)
        self.line_8.setGeometry(QtCore.QRect(0, 90, 601, 16))
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.line_9 = QtWidgets.QFrame(self.page_3)
        self.line_9.setGeometry(QtCore.QRect(0, 320, 601, 16))
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.label_7 = QtWidgets.QLabel(self.page_3)
        self.label_7.setGeometry(QtCore.QRect(20, 340, 301, 61))
        self.label_7.setStyleSheet("font: 6pt \"MS Shell Dlg 2\";")
        self.label_7.setObjectName("label_7")
        self.noThanksBtn = QtWidgets.QPushButton(self.page_3)
        self.noThanksBtn.setGeometry(QtCore.QRect(310, 360, 101, 21))
        self.noThanksBtn.setStyleSheet("font: 6pt \"MS Shell Dlg 2\";")
        self.noThanksBtn.setObjectName("noThanksBtn")
        self.label_8 = QtWidgets.QLabel(self.page_3)
        self.label_8.setGeometry(QtCore.QRect(20, 100, 421, 41))
        self.label_8.setStyleSheet("font: bold 10pt \"MS Shell Dlg 2\";")
        self.label_8.setObjectName("label_8")
        MainSetupWindow.addWidget(self.page_3)

        self.retranslateUi(MainSetupWindow)
        MainSetupWindow.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainSetupWindow)

   # def setGlobalIndex(self):
  #      global globalIndex
 #       globalIndex = 1


    def radioCheck1 (self):
        print ("RadioFull")
        self.globalIndex = 3



    def radioCheck2 (self):
        print ("RadioCustom")
        self.globalIndex = 2



    def retranslateUi(self, MainSetupWindow):
        _translate = QtCore.QCoreApplication.translate
        MainSetupWindow.setWindowTitle(_translate("MainSetupWindow", "Setup"))
        self.buttonCancel2.setText(_translate("MainSetupWindow", "Cancel"))
        self.buttonNext2.setText(_translate("MainSetupWindow", "Next"))
        self.label.setText(_translate("MainSetupWindow", "This Setup will install the AmazeSoft Free Video Converter on your computer.\n"
"\n"
"By clicking \"next\" you agree to the terms & conditions of our End-User License Agreement. Read it online at www.awesomesoft.com/termsandconditions "))
        self.label_2.setText(_translate("MainSetupWindow", "Welcome to the AwesomeSoft Free Video Converter Setup Assistant"))
        self.buttonBack3.setText(_translate("MainSetupWindow", "Back"))
        self.buttonNext3.setText(_translate("MainSetupWindow", "Next"))
        self.label_3.setText(_translate("MainSetupWindow", "Select the components you would like to install. Full installation is recommended!"))
        self.installRadioFull.setText(_translate("MainSetupWindow", "Full Installation (Recommended!)"))
        self.label_4.setText(_translate("MainSetupWindow", "Select Type of Setup"))
        self.installRadioCustom.setText(_translate("MainSetupWindow", "Custom Installation (Advanced Users Only!)"))
        self.label_5.setText(_translate("MainSetupWindow", "Custom Setup"))
        self.checkBox.setText(_translate("MainSetupWindow", "Main Program: AwesomeSoft Free Video Converter (required)"))
        self.checkBox_2.setText(_translate("MainSetupWindow", "Mindsparkle Browser Toolbar"))
        self.checkBox_3.setText(_translate("MainSetupWindow", "Babylona Toolbar"))
        self.checkBox_4.setText(_translate("MainSetupWindow", "TrendDeals Browse"))
        self.checkBox_5.setText(_translate("MainSetupWindow", "FreeSoft PrizeKing"))
        self.checkBox_6.setText(_translate("MainSetupWindow", "YourNewWebSearch"))
        self.checkBox_7.setText(_translate("MainSetupWindow", "Cool Emojis 4 You (hilarious)"))
        self.checkBox_8.setText(_translate("MainSetupWindow", "AskMe.com Toolbar"))
        self.checkBox_9.setText(_translate("MainSetupWindow", "WhoFarted? Browser Extention"))
        self.checkBox_11.setText(_translate("MainSetupWindow", "Some more random Pop-Up Ads"))
        self.checkBox_12.setText(_translate("MainSetupWindow", "BuyBetter"))
        self.checkBox_13.setText(_translate("MainSetupWindow", "Hello123 Search"))
        self.checkBox_14.setText(_translate("MainSetupWindow", "ZinkBrowserManager"))
        self.checkBox_15.setText(_translate("MainSetupWindow", "ZeroUseToolbar"))
        self.checkBox_16.setText(_translate("MainSetupWindow", "TrendBox"))
        self.checkBox_18.setText(_translate("MainSetupWindow", "BetterPriceScout"))
        self.checkBox_20.setText(_translate("MainSetupWindow", "Don\'t uncheck me, please!"))
        self.checkBox_21.setText(_translate("MainSetupWindow", "Questbert Search"))
        self.checkBox_22.setText(_translate("MainSetupWindow", "Geenie Search"))
        self.checkBox_23.setText(_translate("MainSetupWindow", "SafeCom Search"))
        self.checkBox_24.setText(_translate("MainSetupWindow", "YourFavouriteGadgets"))
        self.checkBox_25.setText(_translate("MainSetupWindow", "Frank"))
        self.checkBox_26.setText(_translate("MainSetupWindow", "SpeedSearchBrowser"))
        self.checkBox_27.setText(_translate("MainSetupWindow", "AnnoyingShitBar"))
        self.checkBox_28.setText(_translate("MainSetupWindow", "CrapShare"))
        self.checkBox_29.setText(_translate("MainSetupWindow", "TubeMixer"))
        self.checkBox_30.setText(_translate("MainSetupWindow", "Bullware PC Cleanup"))
        self.checkBox_31.setText(_translate("MainSetupWindow", "WebFace Search"))
        self.checkBox_32.setText(_translate("MainSetupWindow", "Crapsoft UserSpy "))
        self.checkBox_33.setText(_translate("MainSetupWindow", "Yawoo Toolbar"))
        self.checkBox_34.setText(_translate("MainSetupWindow", "GreatDeals"))
        self.checkBox_35.setText(_translate("MainSetupWindow", "A man walks into a toolbar..."))
        self.checkBox_36.setText(_translate("MainSetupWindow", "Ebay Shop Assistant"))
        self.buttonBack4.setText(_translate("MainSetupWindow", "Back"))
        self.buttonNext4.setText(_translate("MainSetupWindow", "Next"))
        self.label_6.setText(_translate("MainSetupWindow", "Custom Setup"))
        self.label_7.setText(_translate("MainSetupWindow", "Click \"install now\" to get SilverWare® Browser CheckUp.\n"
"Otherwise click \"no thanks\" to continue."))
        self.noThanksBtn.setText(_translate("MainSetupWindow", "No thanks, I\'m fine"))
        self.label_8.setText(_translate("MainSetupWindow", "You\'re almost done! Continue the Setup Process?"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainSetupWindow = QtWidgets.QStackedWidget()
    ui = Ui_MainSetupWindow()
    ui.setupUi(MainSetupWindow)
    MainSetupWindow.show()
    sys.exit(app.exec_())

